version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo $CODEBUILD_RESOLVED_SORCE_VERSION > Version
      - echo $CODEBUILD_SRC_DIR
      - cd app/
      - python --version
      - pip install bandit flake8
      - pip install -r $CODEBUILD_SRC_DIR/app/requirements.txt
      - make lint
  build:
    commands:
      - echo "Build"
  post_build:
    commands:
      - echo "Post Build"
artifacts:
  files:
    - '**/*'
  discard-paths: no
  secondary-artifacts:
    Code:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - 'app/*'